name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 0 * * 0'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nechry-automation.ch/feed/"
