name: Update README patch

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nechry/github-activity-readme@v0.3.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
